---
- name: Update apt
  apt: update_cache=yes
- name: Install packages
  apt: name={{ item }} state=latest
  with_items:
  - net-tools
  - nano
  - wget
  - curl

- name: Install nginx
  apt: name=nginx state=latest
  notify: Start nginx

- name: Create custom document root
  file: path={{ document_root }} state=directory owner=www-data group=www-data

- name: Copy nginx.conf
  template: src=templates/nginx.conf dest=/etc/nginx/nginx.conf owner=www-data group=www-data
  notify: Reload nginx

- name: Set up HTML file
  copy: src=index.html dest={{ document_root }}/index.html owner=www-data group=www-data
  notify: Check status nginx

- include: handlers/main.yml

