---
- name: Get service facts
  ansible.builtin.service_facts:

- name: Check status nginx
  shell: systemctl restart nginx
  when: ansible_facts.services["nginx.service"].state == "stopped"

- name: Reload nginx
  shell: nginx -s reload
  when: ansible_facts.services["nginx.service"].state == "running"

- name: Start nginx
  shell: systemctl enable nginx && systemctl start nginx
