---
- name: example playbook
  hosts: kuber-slave
  become: yes

  tasks:
    - name: apt update
      apt: update_cache=yes
    - name: Install docker
      apt:
        name: docker.io
        state: present
    - name: start docker service
      service:
        name: docker
        state: started
        enabled: true
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - curl
        - apt-transport-https
        - gpg
    - name: downloadkey
      ansible.builtin.shell:
        cmd: "sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://dl.k8s.io/apt/doc/apt-key.gpg"
    - name: add key
      ansible.builtin.shell:
        cmd: "echo \"deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main\" | sudo tee /etc/apt/sources.list.d/kubernetes.list"
    - name: apt update
      apt: update_cache=yes
    - apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        install_recommends: yes


