version: '1.24'

services:
  github_action_runner:
    container_name: github_runner
    image: gitrunner
    environment:
      GITHUB_RUNNER_TOKEN: AO5GQ762FS2JTKYAK462OY3E7XCEQ 
      URL_REPO: https://github.com/NoFreaze/Md-SA2-24-23
      R_NAME: Runner5
      R_LABELS: self-hosted,Linux
      WORK_DIR: _work
      R_GROUP: Default
    networks:
      - docker
    restart: unless-stopped
  
networks:
  docker:
    driver: bridge

