---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.spec1.capacity.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.spec1.hostPath.path }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: databaseconfig
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.spec2.capacity.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.spec2.hostPath.path }}
