---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-volume
  labels:
    app: {{ .Values.app }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.spec1.capacity.storage }}
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: databaseconfig
  labels:
    app: {{ .Values.app }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.spec2.capacity.storage }}
  storageClassName: manual

