---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: {{ .Values.app }}-pod
        image: {{ .Values.containers.image }}
        ports:
        - containerPort: 8080
          name: {{ .Values.app }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        volumeMounts:
          - name: jenkins-volume
            mountPath: "/var/jenkins_home"
      volumes:
      - name: jenkins-volume
        persistentVolumeClaim:
          claimName: jenkins-volume