---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.app }}-role
rules:
  - apiGroups: ["*"] # "" indicates the core API group
    resources: ["*"]
    verbs: ["*"]