---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-service
  labels:
    app: {{ .Values.app }}
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: {{ .Values.app }}