name: Run ansible playbook
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Run-ansible-playbook-on-debian:
    name: Run ansible playbook on debian
    runs-on: debian-latest
    steps:
      - uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: site.yml
          directory: 2.Ansible/
          key: ${{secrets.KART_SSH_PRIV_KEY}}
          inventory: |
            [all]
            ${{secrets.REMOTE_HOST_IP}} ansible_ssh_port=${{secrets.SSH_PORT}} ansible_ssh_user=${{secrets.SSH_USER}} ansible_ssh_password=${{secrets.SSH_USER_PASSWORD}}
          options: |
            --verbose
      - run: npm help
