name: Run docker
on:
  push:
    branches: [ main ]

jobs:
  Run-docker-on-host:
    name: Run docker on host
    runs-on: [self-hosted]
    steps:
      - name: docker check
        run: docker run -d -p 8080:8080 alpine
