name: Run docker
on:
  push:
    branches: [ main ]

jobs:
  Run-docker-on-host:
    name: Run docker on host
    runs-on: [self-hosted]
    steps:
      - name: List current folder
        run: docker run -u 0 -d -p 8080:8080 -p 50000:50000 -v /data/jenkins:/var/jenkins_home jenkins/jenkins:lts
